### PR TITLE
makes the code up to date 

### PR DESCRIPTION
**Pull request by Fikou**
image

### CODE REVIEW

**Comment by ghost** [comment]
sorry sir you seem to have some merge conflicts can you fix them?

**Comment by Valtosin** [comment]
madman the nani

**Comment by trollbreeder** [comment]
we must revive TGstation, and i am volunteering for maintainer work

**Comment by TetraK1** [comment]
I'm not sure about the cloning removal in this pr

**Comment by tralezab** [comment]
felinids? weird way to test out tattoo system, but seems like a small admin thing so whatever. this surely won't be a problem for years on end

**Comment by HomocidlePancakes** [comment]
This is a relic of the past. I will not allow you to defile it with cats, xenos and “Oranges Nerf Circus” ™️ bullshit.

**Pull request closed without merging**
